# Generated by Django 5.1.7 on 2026-08-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appointment_time_doctortimeslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_pics/'),
        ),
    ]
