# Generated by Django 5.1.7 on 2026-08-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doctorprofile_about_doctorprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='degree_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_docs/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
