# Generated by Django 5.1.7 on 2026-09-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_appointmentdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_otp',
        ),
    ]
