# Generated by Django 5.1.7 on 2026-09-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='search_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
