# Generated by Django on 2026-09-29

from django.db import migrations

def update_doctor2_profile(apps, schema_editor):
    User = apps.get_model('core', 'User')
    DoctorProfile = apps.get_model('core', 'DoctorProfile')
    
    try:
        user = User.objects.get(username='Doctor2')
        profile = DoctorProfile.objects.get(user=user)
        
        # Update with realistic data
        profile.specialization = 'Senior Cardiologist'
        profile.qualifications = 'MBBS, MD (Cardiology), FACC'
        profile.about = 'I am a board-certified cardiologist with over 10 years of experience in diagnosing and treating complex cardiovascular conditions. I am dedicated to providing comprehensive and compassionate care to my patients, specializing in preventative cardiology, heart failure management, and non-invasive cardiac imaging.'
        profile.experience_years = 12
        profile.consultation_fee = 1200
        profile.languages_spoken = 'English, Hindi, Marathi'
        profile.contact = '+91 98765 43210'
        profile.address = 'Apollo Heart Institute, Jubilee Hills, Hyderabad'
        profile.save()
        
        user.first_name = 'Arun'
        user.last_name = 'Sharma'
        user.save()
    except Exception:
        # Ignore if Doctor2 doesn't exist on some environment
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_doctorprofile_search_embedding'),
    ]

    operations = [
        migrations.RunPython(update_doctor2_profile),
    ]
